# -*- coding: utf-8 -*-
"""athlete app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KnAAKClvnwYT03YqRW99D1lV1q1DZjZc
"""



import streamlit as st
import pandas as pd
import joblib

model = joblib.load("injury_model.pkl")

st.title("Athlete Injury Risk Prediction System")

st.write("Enter athlete details to predict injury risk.")

age = st.number_input("Age", 10, 60, 21)
height = st.number_input("Height (cm)", 100, 220, 165)
weight = st.number_input("Weight (kg)", 30, 150, 60)

uchikomi = st.number_input("Uchikomi sessions/week", 0, 20, 4)
nagekomi = st.number_input("Nagekomi sessions/week", 0, 20, 3)
randori = st.number_input("Randori sessions/week", 0, 20, 3)
randori_duration = st.number_input("Avg randori duration (minutes)", 0, 120, 25)
strength = st.number_input("Strength training sessions/week", 0, 10, 3)

intensity = st.slider("Training intensity", 1, 10, 7)
grip_fatigue = st.slider("Grip fatigue level", 1, 10, 6)
lower_fatigue = st.slider("Lower body fatigue", 1, 10, 6)
ukemi = st.slider("Breakfall proficiency", 1, 10, 7)

competitions = st.number_input("Competitions in last 6 months", 0, 30, 3)
weight_cut = st.number_input("Average weight cut (kg)", 0.0, 15.0, 2.0)

ice_baths = st.selectbox("Regular ice baths?", [0, 1])
physio = st.selectbox("Physio sessions?", [0, 1])
exhausted = st.selectbox("Exhausted after randori?", [0, 1])
resist_throws = st.selectbox("Resist throws instead of falling?", [0, 1])
coach = st.selectbox("Train under coach supervision?", [0, 1])
weight_cut_done = st.selectbox("Weight cuts done?", [0, 1])

input_data = pd.DataFrame([{
    'age': age,
    'height (in cm)': height,
    'weight (in kg)': weight,
    'no. of uchikomi sessions/week': uchikomi,
    'no. of nagekomi sessions/week': nagekomi,
    'no. of randori sessions/week': randori,
    'avg randori duration (minutes)': randori_duration,
    'no. of strength training session/week': strength,
    'training intensity': intensity,
    'grip fatigue level': grip_fatigue,
    'lower body fatigue': lower_fatigue,
    'breakfall (ukemi) proficiency': ukemi,
    'no. of competitions played in last 6 months': competitions,
    'avg weight cut in kgs': weight_cut,
    'regular ice baths': ice_baths,
    'physio sessions': physio,
    'do you feel exhausted after randori?': exhausted,
    'do you resist throws instead of falling?': resist_throws,
    'train under coach supervision': coach,
    'weight cuts done?': weight_cut_done
}])

if st.button("Predict Injury Risk"):
    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0][1]

    st.subheader("Prediction Result")
    st.write("Injury Risk Probability:", round(probability * 100, 2), "%")

    if probability >= 0.75:
        st.error("High Injury Risk")
        st.write("- Reduce randori intensity")
        st.write("- Take recovery/physio session")
        st.write("- Avoid weight cut this week")

    elif probability >= 0.45:
        st.warning("Moderate Injury Risk")
        st.write("- Manage training load")
        st.write("- Improve recovery")
        st.write("- Track fatigue daily")

    else:
        st.success("Low Injury Risk")
        st.write("- Maintain current routine")
        st.write("- Continue recovery habits")

