# -*- coding: utf-8 -*-
"""AthleteInjuryRisk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e31cgZSWXnuD-roVwisE8PSNQZaQSRms
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
#

data = pd.read_excel("Athlete Data set.xlsx")

data

data.head(10)



num_rows_to_display = 10 # You can change this number

# Calculate the middle index
middle_index = len(data) // 2

# Determine the start and end indices for the slice
start_index = max(0, middle_index - num_rows_to_display // 2)
end_index = min(len(data), middle_index + num_rows_to_display // 2)

# Adjust end_index if num_rows_to_display is odd or if we hit the beginning/end of the DataFrame
if (end_index - start_index) < num_rows_to_display:
    if start_index == 0:
        end_index = min(len(data), num_rows_to_display)
    elif end_index == len(data):
        start_index = max(0, len(data) - num_rows_to_display)

# Display the rows from the center
display(data.iloc[start_index:end_index])

data.iloc[10:20]

data.shape

data.columns

data.info()

data.isnull().sum()

df = data.drop_duplicates()

df.shape

df.columns = df.columns.str.strip()

df.columns = df.columns.str.lower()

numerical_cols = df.select_dtypes(include=np.number).columns
categorical_cols = df.select_dtypes(exclude=np.number).columns

print(numerical_cols)
print(categorical_cols)

print(df.columns)

df = df.drop('timestamp', axis = 1)

df.columns

df = df.drop(['full name'], axis=1)

def extract_number(value):
    if pd.isna(value):
        return np.nan

    value = str(value).lower().strip()

    # handle U60 type weight category
    value = value.replace("u", "")

    numbers = re.findall(r'\d+\.?\d*', value)

    if len(numbers) == 0:
        return np.nan

    # if range like 3-4 or 3/4, take average
    nums = [float(n) for n in numbers]
    return sum(nums) / len(nums)

num_clean_cols = [
    'height (in cm)',
    'weight (in kg)',
    'no. of uchikomi sessions/week',
    'no. of nagekomi sessions/week',
    'no. of randori sessions/week',
    'avg randori duration (minutes)',
    'no. of strength training session/week',
    'training intensity',
    'grip fatigue level',
    'lower body fatigue',
    'breakfall (ukemi) proficiency',
    'no. of competitions played in last 6 months',
    'avg weight cut in kgs'
]

for col in num_clean_cols:
    df[col] = df[col].apply(extract_number)

def clean_height(value):
    if pd.isna(value):
        return np.nan

    value = str(value).lower().strip()

    # feet inches case
    if "'" in value or '"' in value:
        nums = re.findall(r'\d+', value)
        if len(nums) >= 2:
            feet = int(nums[0])
            inches = int(nums[1])
            return round((feet * 12 + inches) * 2.54, 2)

    return extract_number(value)

df['height (in cm)'] = df['height (in cm)'].apply(clean_height)

yes_no_cols = [
    'regular ice baths',
    'physio sessions',
    'do you feel exhausted after randori?',
    'do you resist throws instead of falling?',
    'train under coach supervision',
    'weight cuts done?'
]

for col in yes_no_cols:
    df[col] = df[col].astype(str).str.lower().str.strip()
    df[col] = df[col].map({'yes': 1, 'no': 0})

df['injury in last 12 months'] = df['injury in last 12 months'].apply(
    lambda x: 1 if 'yes' in str(x).lower() else 0
)

cat_cols = [
    'gender',
    'sport',
    'playing level',
    'injury type',
    'during what activity?',
    'due to'
]

for col in cat_cols:
    df[col] = df[col].astype(str).str.lower().str.strip()

from sklearn.impute import SimpleImputer

numerical_cols = df.select_dtypes(include=np.number).columns
categorical_cols = df.select_dtypes(exclude=np.number).columns

num_imputer = SimpleImputer(strategy='median')
df[numerical_cols] = num_imputer.fit_transform(df[numerical_cols])

cat_imputer = SimpleImputer(strategy='most_frequent')
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

df.head()

df.info()

y = df['injury in last 12 months']
X = df.drop('injury in last 12 months', axis=1)

df.shape

df.info()

df.head()

df['injury in last 12 months'].value_counts()

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(
    x='training intensity',
    hue='injury in last 12 months',
    data=df
)

plt.title("Training Intensity vs Injury")
plt.show()

sns.boxplot(
    x='injury in last 12 months',
    y='grip fatigue level',
    data=df
)

plt.title("Grip Fatigue vs Injury")
plt.show()

sns.countplot(
    x='weight cuts done?',
    hue='injury in last 12 months',
    data=df
)

plt.title("Weight Cuts vs Injury")
plt.show()

sns.boxplot(
    x='injury in last 12 months',
    y='avg weight cut in kgs',
    data=df
)

plt.title("Weight Cut Amount vs Injury")
plt.show()

sns.boxplot(
    x='injury in last 12 months',
    y='avg randori duration (minutes)',
    data=df
)

plt.title("Randori Duration vs Injury")
plt.show()

plt.figure(figsize=(15,10))

sns.heatmap(
    df.corr(),
    annot=False,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()

sns.boxplot(
    x='injury in last 12 months',
    y='no. of competitions played in last 6 months',
    data=df
)

plt.title("Competition Load vs Injury")
plt.show()

sns.countplot(
    x='regular ice baths',
    hue='injury in last 12 months',
    data=df
)

plt.title("Ice Baths vs Injury")
plt.show()

sns.countplot(
    x='train under coach supervision',
    hue='injury in last 12 months',
    data=df
)

plt.title("Coach Supervision vs Injury")
plt.show()

#EDA
#The exploratory data analysis suggests that athlete injuries are influenced by multiple workload and recovery-related factors.

#Variables such as training intensity, weight cutting, and competition exposure showed noticeable relationships with injury occurrence.

#On the other hand, isolated factors like grip fatigue and randori duration did not independently show strong differences between injured and non-injured athletes.

#The findings indicate that injury risk assessment in combat sports should consider a combination of physical load, recovery behavior, and athlete management variables rather than relying on a single metric.

#Some inconsistencies and outliers were observed in the dataset due to self-reported survey responses. Appropriate preprocessing and cleaning techniques were applied to improve data quality before analysis.

y = df['injury in last 12 months']

X = df.drop('injury in last 12 months', axis=1)

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

kfold = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    model,
    X,
    y,
    cv=kfold,
    scoring='accuracy'
)

print("Scores for each fold:", scores)
print("Average Accuracy:", scores.mean())

recall_scores = cross_val_score(
    model,
    X,
    y,
    cv=kfold,
    scoring='recall'
)

print("Recall for each fold:", recall_scores)
print("Average Recall:", recall_scores.mean())

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)

skfold = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

accuracy = cross_val_score(model, X, y, cv=skfold, scoring='accuracy')
recall = cross_val_score(model, X, y, cv=skfold, scoring='recall')
f1 = cross_val_score(model, X, y, cv=skfold, scoring='f1')

print("Accuracy:", accuracy)
print("Average Accuracy:", accuracy.mean())

print("Recall:", recall)
print("Average Recall:", recall.mean())

print("F1:", f1)
print("Average F1:", f1.mean())

from sklearn.model_selection import StratifiedKFold, cross_val_score

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),

    "Decision Tree": DecisionTreeClassifier(random_state=42),

    "Random Forest": RandomForestClassifier(random_state=42),

    "Gradient Boosting": GradientBoostingClassifier(random_state=42),

    "SVM": SVC()
}

skfold = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

for name, model in models.items():

    accuracy = cross_val_score(
        model,
        X,
        y,
        cv=skfold,
        scoring='accuracy'
    )

    recall = cross_val_score(
        model,
        X,
        y,
        cv=skfold,
        scoring='recall'
    )

    f1 = cross_val_score(
        model,
        X,
        y,
        cv=skfold,
        scoring='f1'
    )

    print(f"\n{name}")

    print("Accuracy:", accuracy.mean())
    print("Recall:", recall.mean())
    print("F1 Score:", f1.mean())

best_model = RandomForestClassifier(random_state=42)

best_model.fit(X, y)

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': best_model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

print(importance.head(10))

import matplotlib.pyplot as plt

top_features = importance.head(10)

plt.figure(figsize=(10,6))

plt.barh(
    top_features['Feature'],
    top_features['Importance']
)

plt.xlabel("Importance")
plt.title("Top Injury Risk Factors")

plt.gca().invert_yaxis()

plt.show()

#KEY Obs
#Random Forest achieved the highest recall score among all models, making it the most suitable model for injury risk prediction.

#Training intensity, weight cuts, and competition exposure emerged as the most influential features affecting injury occurrence.

import joblib

joblib.dump(best_model, 'injury_prediction_model.pkl')



