# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SNbdqL8sZQMKYkVdm103q99DDDdxEnoT
"""

import joblib

model = joblib.load(
    "injury_model.pkl"
)

import pandas as pd

new_athlete = pd.DataFrame([{

    'age': 22,
    'height (in cm)': 170,
    'weight (in kg)': 63,

    'no. of uchikomi sessions/week': 6,
    'no. of nagekomi sessions/week': 5,
    'no. of randori sessions/week': 4,

    'avg randori duration (minutes)': 35,

    'no. of strength training session/week': 4,

    'training intensity': 9,

    'grip fatigue level': 8,

    'lower body fatigue': 8,

    'breakfall (ukemi) proficiency': 6,

    'no. of competitions played in last 6 months': 6,

    'avg weight cut in kgs': 4,

    'regular ice baths': 0,

    'physio sessions': 0,

    'do you feel exhausted after randori?': 1,

    'do you resist throws instead of falling?': 1,

    'train under coach supervision': 1,

    'weight cuts done?': 1
}])

prediction = model.predict(
    new_athlete
)

probability = model.predict_proba(
    new_athlete
)

print("Prediction:", prediction)

print(
    "Injury Risk Probability:",
    probability[0][1]
)

risk = probability[0][1]

if risk >= 0.75:
    level = "High Risk"
    advice = [
        "Reduce randori intensity for a few days",
        "Add recovery/physio session",
        "Avoid weight cut this week",
        "Monitor fatigue and sleep"
    ]

elif risk >= 0.45:
    level = "Moderate Risk"
    advice = [
        "Control training load",
        "Improve recovery",
        "Track fatigue after randori"
    ]

else:
    level = "Low Risk"
    advice = [
        "Maintain current training routine",
        "Continue proper recovery habits"
    ]

print("Risk Level:", level)
print("Recommendations:")

for a in advice:
    print("-", a)

