# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHU_jqawQrO7ssqwri9wZ64phSIrp9VY
"""

import pandas as pd

df = pd.read_csv(
    "synthetic_athlete_dataset.csv"
)

print(df.head())

X = df.drop(
    'injury in last 12 months',
    axis=1
)

y = df['injury in last 12 months']

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X, y)

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    model,
    X,
    y,
    cv=skf,
    scoring='recall'
)

print(scores)
print(scores.mean())

import joblib

joblib.dump(
    model,
    "injury_model.pkl"
)



